### PR TITLE
Correct A157

### PR DESCRIPTION
**Pull request by epistularum**

### CODE REVIEW

**Comment by Thermospore** [comment]
Afaict that is `ʿ` https://en.wikipedia.org/wiki/Modifier_letter_left_half_ring

I think it needs to stay as `‘` to match up with the other quote such as in アシュラ
image

image

original html for ref
`アシュラ 【<object class=""gaiji"" data=""A157.svg""></object>Āshūrā’ アラビア】`

**Comment by epistularum** [comment]
I do not believe this is a quote but rather a character that denotes pronunciation in arabic romanization.
image

**Comment by Thermospore** [comment]
ah ok you are probably right, I will take another look

**Comment by Thermospore** [comment]
thanks for pointing this out! kinda embarrassing I missed this, it's nice to have a second pair of eyes on these! (I guess technically shoui made it so im the second pair of eyes and you are the third but you get the point lol)

this turned out to be a bit of a rabbit hole

I looked into it a bit and yeah afaict the gaiji is functionally an arabic ayn. arabic transliteration seems to be a bit of a mess... quick info dump:

- [comparison table of different systems](https://en.wikipedia.org/wiki/Romanization_of_Arabic#Comparison_table)
- [examples](https://en.wikipedia.org/wiki/Romanization_of_Arabic#Examples)
- [on ayn transliteration/unicode](https://en.wikipedia.org/wiki/Ayin#Transliteration)

so I think ideally yes `ʿ` should be used for ayn and `ʾ` for hamzah (the half circles)

- image
- image
- image

BUT koj is using `’` for hamzah instead of the right half circle `ʾ`, for their transliteration system. so it would be a mismatch to use `ʿ` + `’`, instead of `‘` + `’`, I think

it might be a font difference, but the svg does seem more like a `‘` than a `ʿ` as well
image
 
this does bring up some questions though. like if it is actually `‘`, why does koj use a gaiji for it when they don't need a gaiji for `’` (the adjacent codepoint in unicode)?

BUT WAIT it gets even more confusing: koj does actually use `‘` (verbatim, not using a gaiji) for ayn in many entries
- image
- image

I'm not sure if there is an intended distinction, between when koj uses the gaiji vs the unicode

this type of inconsistency isn't terribly surprising; there are other formatting oddities/inconsistencies like this throughout the data. maybe one author used gaiji and another just used the character, or styles drifted between editions, etc who knows

for easy ref, here are all the entries that use A157.svg:
```
"アシュラ 【<object class=""gaiji"" data=""A157.svg""></object>Āshūrā’ アラビア】","<rn></rn><a name=""000181050000""></a><div class=""midashi"">アシュラ 【<object class=""gaiji"" data=""A157.svg""></object>Āshūrā’ アラビア】</div><div class=""honbun""><rn></rn><a name=""000181050001""></a><div style=""margin-left:1em;"">イスラム暦1月10日のこと。シーア派の最大宗派十二イマーム派では、第3代イマームのフセインが、イスラム暦61年（西暦680年）のこの日にカルバラーで殉教したことを哀悼する行事を大々的に行う。アーシューラー。</div></div>"
"アッタール 【Farīd al-Dīn <object class=""gaiji"" data=""A157.svg""></object>Aṭṭār】","<rn></rn><a name=""000226550000""></a><div class=""midashi"">アッタール 【Farīd al-Dīn <object class=""gaiji"" data=""A157.svg""></object>Aṭṭār】</div><div class=""honbun""><rn></rn><a name=""000226550001""></a><div style=""margin-left:1em;"">（「香料商」の意の雅号）ペルシアの神秘主義詩人。叙事詩「鳥の言葉」、散文「神秘主義聖者列伝」など。（1145頃～1221または1145頃～1229頃）</div></div>"
イクター‐せい 【イクター制】,"<rn></rn><a name=""000511750000""></a><div class=""midashi"">イクター‐せい 【イクター制】</div><div class=""honbun""><rn></rn><a name=""000511750001""></a><div style=""margin-left:1em;"">（iqṭā<object class=""gaiji"" data=""A157.svg""></object> アラビア）中世イスラム世界の経済社会体制。君主が軍人に分与地（イクター）を授与し、土地の管理と徴税権を委ねる制度に立脚する。</div></div>"
イ‐テジュン 【李泰俊】,"<rn></rn><a name=""000689900000""></a><div class=""midashi"">イ‐テジュン 【李泰俊】</div><div class=""honbun""><rn></rn><a name=""000689900001""></a><div style=""margin-left:1em;"">（I T<object class=""gaiji"" data=""A157.svg""></object>ae-jun）朝鮮の作家。江原道鉄原出身。号は尚虚。朝鮮近代小説の技法的基盤を作る。作「鴉」「福徳房」など。1946年訪ソ後は北朝鮮に在住。（1904～<object class=""gaiji"" data=""B731.svg""></object><object class=""gaiji"" data=""B731.svg""></object>）</div></div>"
"グルガーニー 【Fakhr al-Dīn As<object class=""gaiji"" data=""A157.svg""></object>ad Gurgānī】","<rn></rn><a name=""003287500000""></a><div class=""midashi"">グルガーニー 【Fakhr al-Dīn As<object class=""gaiji"" data=""A157.svg""></object>ad Gurgānī】</div><div class=""honbun""><rn></rn><a name=""003287500001""></a><div style=""margin-left:1em;"">セルジューク朝期のペルシア語詩人。恋愛叙事詩「ヴィースとラーミーン」で知られる。（<object class=""gaiji"" data=""B731.svg""></object><object class=""gaiji"" data=""B731.svg""></object>～1073以後）</div></div>"
"サアダーウィー 【Nawāl al-Sa<object class=""gaiji"" data=""A157.svg""></object>dāwī】","<rn></rn><a name=""004300900000""></a><div class=""midashi"">サアダーウィー 【Nawāl al-Sa<object class=""gaiji"" data=""A157.svg""></object>dāwī】</div><div class=""honbun""><rn></rn><a name=""004300900001""></a><div style=""margin-left:1em;"">エジプトのフェミニスト作家・精神科医。著「零度の女」「イヴの隠れた顔」など。（1931～）</div></div>"
サムゲタン 【参鶏湯】,"<rn></rn><a name=""004547800000""></a><div class=""midashi"">サムゲタン 【参鶏湯】</div><div class=""honbun""><rn></rn><a name=""004547800001""></a><div style=""margin-left:1em;"">（朝鮮語samgyet<object class=""gaiji"" data=""A157.svg""></object>ang）鶏の腹に糯米<sub class=""rubi"">もちごめ</sub>・栗・なつめ・朝鮮人参などを詰めて煮込んだ料理。</div></div>"
"ジャマールザーデ 【Moḥammad <object class=""gaiji"" data=""A157.svg""></object>Alī Jamālzādeh】","<rn></rn><a name=""005182050000""></a><div class=""midashi"">ジャマールザーデ 【Moḥammad <object class=""gaiji"" data=""A157.svg""></object>Alī Jamālzādeh】</div><div class=""honbun""><rn></rn><a name=""005182050001""></a><div style=""margin-left:1em;"">イランの作家。エスファハン生れ。ヨーロッパで活動。現代ペルシア散文の先駆者。短編集「昔々」、長編「精神病院」など。（1892～1997）</div></div>"
じゅうに‐イマーム‐は 【十二イマーム派】,"<rn></rn><a name=""005262950000""></a><div class=""midashi"">じゅうに‐イマーム‐は 【十二イマーム派】 <sub>ジフ‥</sub></div><div class=""honbun""><rn></rn><a name=""005262950001""></a><div style=""margin-left:1em;"">（Ithnā <object class=""gaiji"" data=""A157.svg""></object>Asharīya アラビア）イスラム教シーア派の最大宗派。アリーとその子孫の中から11人、計12人をイマーム（最高指導者）と認めることからの称。イランでは支配的。イラク・レバノン・バーレーンなどにも多い。</div></div>"
チェ‐ナムソン 【崔南善】,"<rn></rn><a name=""007149950000""></a><div class=""midashi"">チェ‐ナムソン 【崔南善】</div><div class=""honbun""><rn></rn><a name=""007149950001""></a><div style=""margin-left:1em;"">（Ch<object class=""gaiji"" data=""A157.svg""></object>oe Nam-sŏn）朝鮮の詩人・評論家・出版人。ソウル生れ。号は六堂。自由詩「海から少年へ」は朝鮮近代詩の嚆矢。三‐一独立宣言文を起草。（1890～1957）</div></div>"
ちん‐すいへん 【陳水扁】,"<rn></rn><a name=""007402350000""></a><div class=""midashi"">ちん‐すいへん 【陳水扁】</div><div class=""honbun""><rn></rn><a name=""007402350001""></a><div style=""margin-left:1em;"">（Chen Shuibian; Ch<object class=""gaiji"" data=""A157.svg""></object>ên Shui-pien）台湾の政治家。台南生れ。台湾大学卒業後、弁護士として活動。1987年民進党に加入し、94年初の民選台北市長、2000～08年中華民国総統。（1950～）</div></div>"
"ブルギバ 【al-Ḥabīb ibn <object class=""gaiji"" data=""A157.svg""></object>Alī al-Būrqība】","<rn></rn><a name=""009922400000""></a><div class=""midashi"">ブルギバ 【al-Ḥabīb ibn <object class=""gaiji"" data=""A157.svg""></object>Alī al-Būrqība】</div><div class=""honbun""><rn></rn><a name=""009922400001""></a><div style=""margin-left:1em;"">チュニジアの政治家。独立運動を指導、初代大統領（1957～1987）。経済・社会の近代化を推進。（1903～2000）</div></div>"
ホン‐ナンパ 【洪蘭坡】,"<rn></rn><a name=""010411200000""></a><div class=""midashi"">ホン‐ナンパ 【洪蘭坡】</div><div class=""honbun""><rn></rn><a name=""010411200001""></a><div style=""margin-left:1em;"">（Hong Nan-p<object class=""gaiji"" data=""A157.svg""></object>a）朝鮮の洋楽家。本名、永厚。創氏名、森川潤。京畿道水原生れ。歌曲「鳳仙花」「愛」、童謡「故郷の春」などを作曲。（1898～1941）</div></div>"
"マアッリー 【Abū al-<object class=""gaiji"" data=""A157.svg""></object>Alā’ al-Ma<object class=""gaiji"" data=""A157.svg""></object>arrī】","<rn></rn><a name=""010426500000""></a><div class=""midashi"">マアッリー 【Abū al-<object class=""gaiji"" data=""A157.svg""></object>Alā’ al-Ma<object class=""gaiji"" data=""A157.svg""></object>arrī】</div><div class=""honbun""><rn></rn><a name=""010426500001""></a><div style=""margin-left:1em;"">シリア出身のアラブ文学者。幼時に失明。作に、高い学識と技巧による詩集「火打石の閃光」「無用な義務の強制」、散文体の天路歴程譚「赦しの書簡」。（973～1057）</div></div>"
```

and here are some entries that use `‘` verbatim, without using a gaiji:
```
ウード 【‘ūd アラビア】,"<rn></rn><a name=""000880750000""></a><div class=""midashi"">ウード 【‘ūd アラビア】</div><div class=""honbun""><rn></rn><a name=""000880750001""></a><div style=""margin-left:1em;"">西アジア起源の撥弦楽器。北アフリカから西アジアにかけて広く用いられる。通常4～6コースの複弦で、細長い撥<sub class=""rubi"">ばち</sub>ではじく。ヨーロッパのリュートの祖。<div class=""media""><img class=""FIGs"" src=""S00155.jpg""></img></div></div></div>"
ウェード 【Thomas Francis Wade】,"<rn></rn><a name=""000882900000""></a><div class=""midashi"">ウェード 【Thomas Francis Wade】</div><div class=""honbun""><rn></rn><a name=""000882900001""></a><div style=""margin-left:1em;"">イギリスの軍人・外交官・中国研究家。漢名は威妥瑪。阿片戦争に際し渡清。ローマ字による中国語の表記に、「<q class=""siki"">‘</q>」を付して有気音と無気音とを区別し、1・2・3・4で四声を示すいわゆるウェード式を創案。（1818～1895）</div></div>"
ウスマーン 【‘Uthmān アラビア】,"<rn></rn><a name=""000958400000""></a><div class=""midashi"">ウスマーン 【‘Uthmān アラビア】</div><div class=""honbun""><rn></rn><a name=""000958400001""></a><div style=""margin-left:1em;"">イスラムの第3代正統カリフ（在位644～656）。コーランを1冊の書物の形に結集。オスマン。（<object class=""gaiji"" data=""B731.svg""></object><object class=""gaiji"" data=""B731.svg""></object>～656）</div></div>"
ウマル 【‘Umar】,"<rn></rn><a name=""001044500000""></a><div class=""midashi"">ウマル 【‘Umar】</div><div class=""honbun""><rn></rn><a name=""001044500001""></a><div style=""margin-left:1em;"">イスラムの第2代正統カリフ。イスラム国家の基礎の建設者。イスラム暦を制定。オマル。（在位634～644）（<object class=""gaiji"" data=""B731.svg""></object><object class=""gaiji"" data=""B731.svg""></object>～644）</div></div>"
ウマル‐ハイヤーム 【‘Umar Khayyām】,"<rn></rn><a name=""001044650000""></a><div class=""midashi"">ウマル‐ハイヤーム 【‘Umar Khayyām】</div><div class=""honbun""><rn></rn><a name=""001044650001""></a><div style=""margin-left:1em;"">イランの天文学者・数学者・詩人。四行詩「ルバイヤート」は19世紀に英訳され、広く愛誦されてきた。オマル＝ハイヤーム。（1048～1131）</div></div>"
ウラマー 【‘ulamā’ アラビア】,"<rn></rn><a name=""001074100000""></a><div class=""midashi"">ウラマー 【‘ulamā’ アラビア】</div><div class=""honbun""><rn></rn><a name=""001074100001""></a><div style=""margin-left:1em;"">（「知者たち」の意）イスラムの諸学問の学者たちの総称。法学・神学・啓典解釈学・ハディース学などの専門家で、イスラム法の解釈と運用を通じて社会に重きをなす。ウレマー。オラマー。</div></div>"
オイ‐キムチ,"<rn></rn><a name=""001308200000""></a><div class=""midashi"">オイ‐キムチ</div><div class=""honbun""><rn></rn><a name=""001308200001""></a><div style=""margin-left:1em;"">（朝鮮語oi kimch‘i）キュウリのキムチ。</div></div>"
オマル‐ハイヤーム 【‘Umar Khayyām】,"<rn></rn><a name=""001618750000""></a><div class=""midashi"">オマル‐ハイヤーム 【‘Umar Khayyām】</div><div class=""honbun""><rn></rn><a name=""001618750001""></a><div style=""margin-left:1em;""> <a href=""lved.dataid:00104465""><object class=""icon"" data=""yajirusi1.svg""></object>ウマル＝ハイヤーム</a></div></div>"
カーバ 【ka‘bah アラビア・Kaaba イギリス】,"<rn></rn><a name=""001724650000""></a><div class=""midashi"">カーバ 【ka‘bah アラビア・Kaaba イギリス】</div><div class=""honbun""><rn></rn><a name=""001724650001""></a><div style=""margin-left:1em;"">（「立方体の建物」の意）メッカにある石造の聖殿。「神の館」と呼ばれ、唯一神の存在を象徴。聖殿とそれを囲むハラーム‐モスクはイスラム第一の聖地。イスラム教徒は礼拝の際にカーバの方角を向き、メッカ巡礼ではその回りを7周する。カアバ。</div></div>"
カダフィ 【Mu‘ammar al-Qadhdhāfī】,"<rn></rn><a name=""002109300000""></a><div class=""midashi"">カダフィ 【Mu‘ammar al-Qadhdhāfī】</div><div class=""honbun""><rn></rn><a name=""002109300001""></a><div style=""margin-left:1em;"">リビアの軍人・政治家。1969年王政を廃止し、同国を40年余り独裁的に支配。反政府勢力との内戦が起き、殺害された。（1942～2011）</div></div>"
カムルチー,"<rn></rn><a name=""002284300000""></a><div class=""midashi"">カムルチー</div><div class=""honbun""><rn></rn><a name=""002284300001""></a><div style=""margin-left:1em;"">（朝鮮語kamulch‘i）タイワンドジョウ科の淡水産の硬骨魚。全長30～85センチメートル。アジア大陸東部原産。日本へは朝鮮から移入されたらしく、南西諸島を除く全国に分布。食性は類縁種のタイワンドジョウに似て、他の魚を食害。空気呼吸もできる。雷魚。</div></div>"
キムチ 【沈菜】,"<rn></rn><a name=""002756600000""></a><div class=""midashi"">キムチ 【沈菜】</div><div class=""honbun""><rn></rn><a name=""002756600001""></a><div style=""margin-left:1em;"">（朝鮮語kimch‘i）朝鮮の漬け物。塩漬にした野菜に、ニンニク・ショウガ・トウガラシ・塩辛などを合わせて漬け込む。</div></div>"
キムポ 【金浦】,"<rn></rn><a name=""002757150000""></a><div class=""midashi"">キムポ 【金浦】</div><div class=""honbun""><rn></rn><a name=""002757150001""></a><div style=""margin-left:1em;"">（Kimp‘o）韓国京畿道西部の都市。ソウルに近接し、韓国有数の稲作地帯で、園芸農業も発達。南東のソウル市江西区に金浦空港（もと金浦郡内）がある。</div></div>"
コチュジャン,"<rn></rn><a name=""004073900000""></a><div class=""midashi"">コチュジャン</div><div class=""honbun""><rn></rn><a name=""004073900001""></a><div style=""margin-left:1em;"">（朝鮮語koch‘ujang コチュは唐辛子、ジャンは味噌などのペースト状のものの意）朝鮮料理に用いる調味料で、唐辛子を加えた味噌。</div></div>"
サアディー 【Sa‘dī】,"<rn></rn><a name=""004301350000""></a><div class=""midashi"">サアディー 【Sa‘dī】</div><div class=""honbun""><rn></rn><a name=""004301350001""></a><div style=""margin-left:1em;"">ペルシアを代表する教訓・道徳詩人。神秘主義の教養を積み、三十余年諸国を放浪して得た貴重な体験を代表作「果樹園」「薔薇<sub class=""rubi"">ばら</sub>園」に著す。（1213頃～1291頃）</div></div>"
サヌア 【Ṣan‘ā’】,"<rn></rn><a name=""004525800000""></a><div class=""midashi"">サヌア 【Ṣan‘ā’】</div><div class=""honbun""><rn></rn><a name=""004525800001""></a><div style=""margin-left:1em;"">イエメン共和国の首都。アラビア半島南部最大の都市で、標高約2300メートルの高地に位置する。古くからイスラム都市として栄える。伝統的な旧市街が保存され、世界遺産。サナア。人口197万6千(2009)。</div></div>"
サンチュ,"<rn></rn><a name=""004652600000""></a><div class=""midashi"">サンチュ</div><div class=""honbun""><rn></rn><a name=""004652600001""></a><div style=""margin-left:1em;"">（朝鮮語sangch‘u）朝鮮の代表的な葉菜で、萵苣<sub class=""rubi"">ちしゃ</sub>の一種。焼肉などを包んで食べる。</div></div>"
シーア‐は 【シーア派】,"<rn></rn><a name=""004704400000""></a><div class=""midashi"">シーア‐は 【シーア派】</div><div class=""honbun""><rn></rn><a name=""004704400001""></a><div style=""margin-left:1em;"">（Shī‘a アラビア 党派の意）イスラムの一派。ムハンマドの従弟で4代カリフのアリーおよびその家系をイスラム共同体の正しい指導者（イマーム）とする諸分派の総称。その中ではイラン・イラクなどに広がる十二イマーム派が最大。 <a href=""lved.dataid:00610445"">→スンニー派</a></div></div>"
しべん‐しんがく 【思弁神学】,"<rn></rn><a name=""005069850000""></a><div class=""midashi"">しべん‐しんがく 【思弁神学】</div><div class=""honbun""><rn></rn><a name=""005069850001""></a><div style=""margin-left:1em;"">（‘ilm al-kalām アラビア）イスラムで、聖典の教えと論理的考察とを総合する神学。ギリシアの哲学や論理学の影響を受けて8～10世紀に成立。アシュアリー学派・マートゥリーディー学派などがある。</div><rn></rn><a name=""005069850001""></a><div class=""oyko_link""><object class=""icon"" data=""yajirusi2.svg""></object><a href=""lved.dataid:00506955"">し‐べん 【思弁】</a></div></div>"
シャーフィイー 【Abū ‘Abdullāh Muḥammad al-Shāfi‘ī】,"<rn></rn><a name=""005121650000""></a><div class=""midashi"">シャーフィイー 【Abū ‘Abdullāh Muḥammad al-Shāfi‘ī】</div><div class=""honbun""><rn></rn><a name=""005121650001""></a><div style=""margin-left:1em;"">アラブ人のイスラム法学者・法理論家。スンニー派のシャーフィイー法学派の祖。ガザに生まれ、カイロで没。イスラム法理論を最初に体系化。著「論考」など。（767～820）</div></div>"
ジャーミー 【jāmi‘ アラビア】,"<rn></rn><a name=""005122150000""></a><div class=""midashi"">ジャーミー 【jāmi‘ アラビア】</div><div class=""honbun""><rn></rn><a name=""005122150001""></a><div style=""margin-left:1em;"">（masjid jāmi‘（金曜モスク）の略）イスラムで、金曜日の集団礼拝を行う大規模なモスク。大モスク。</div></div>"
シャトル‐アラブ 【Shaṭṭ al-‘Arab】,"<rn></rn><a name=""005174650000""></a><div class=""midashi"">シャトル‐アラブ 【Shaṭṭ al-‘Arab】</div><div class=""honbun""><rn></rn><a name=""005174650001""></a><div style=""margin-left:1em;"">ティグリス川とユーフラテス川を合わせてペルシア湾に注ぐ川。全長約195キロメートル。下流でイランとイラクの国境をなす。</div></div>"
シャリーア 【sharī‘a アラビア】,"<rn></rn><a name=""005187950000""></a><div class=""midashi"">シャリーア 【sharī‘a アラビア】</div><div class=""honbun""><rn></rn><a name=""005187950001""></a><div style=""margin-left:1em;"">イスラム法のこと。</div></div>"
```

**Comment by Thermospore** [comment]
Basically, AFAICT `ʿ` is the correct character, but it should be left as `‘` for consistency. I will close this pull request for now unless anyone has objections

**Pull request closed without merging**
