### PR TITLE
correct A53D.svg

### PR DESCRIPTION
**Pull request by epistularum**

### CODE REVIEW

**Comment by Thermospore** [comment]
actually, maybe we should use 莔, as in 莔麻(イチビ)?

https://ja.wikipedia.org/wiki/%E3%82%A4%E3%83%81%E3%83%93

莔麻(イチビ) is the only word A53D.svg is used in for the whole dict, and 莔麻 seems to dominate over 苘麻 or 𦯶麻

**Comment by epistularum** [comment]
I have found quite a few errors before in wikipedia when it comes to kanji representation of animal/plant names. I believe that 莔 苘 might be used as a 代用字 for A53D as this character probably didn't to used to exist in unicode or even jis for a while. (a bit like what is going with 剥く and 剝く or 叱 and 𠮟).

𦯶 is the actual correct unicode representation of the provided svg, I believe there is a reason why 岩波 purposefully used this form in the svg and not something else. Most likely the reason that it is provided in svg and not in unicode is that the used font doesn't support 𦯶. If they wanted to use the 代用字 they wouldn't have made a svg in the first place because these are supported by the font.

Furthermore, this character is actually used in 
デジタル大辞泉 
image

and 日本国語大辞典.
image

**Comment by Thermospore** [comment]
Thanks for the info, good points, I'm sold

Maybe it is best to have an explicit policy on 代用字 vs svg vs strictly correct unicode mapping

- 代用字 pros are it makes entries more searchable, but the cons are that you deviate from the author's intention. so yea generally best to avoid, I think, especially for archival purposes

- strictly correct unicode mapping is usually ideal, but the problem is sometimes the character is so wildly obscure it basically doesn't exist in any font. There are some chars I found the unicode mapping for, but [decided to leave as svg at the time](https://github.com/Thermospore/koj72yomi/commit/b0b691363e4cb8d6fac2eb5c547627cc1a8094c5), for this reason. 𦯶 might be on the edge; it doesn't show up at all on my phone or my watch, but it at least shows up on my computer (though only in a fallback chinese font, I think)

- and ofc svg is exact author intention, but entirely unsearchable

**Comment by epistularum** [comment]
Given the fact that we're mostly dealing with edge cases I think it would be fine sticking to the original svg when no exact unicode representation can be found. For the same reason of those being edge cases I think it is also fine having an unicode that is very rare and hardly supported by most fonts.

Concerning the font issue you should install 花園, it's a font that supports ALL unicode characters. It is compiled based on the data provided by the glyphwiki. Unfortunately it currently only has 明朝 variant but they're apparently working on a ゴシック variant as well.
image

**Comment by Thermospore** [comment]
> Given the fact that we're mostly dealing with edge cases I think it would be fine sticking to the original svg when no exact unicode representation can be found. For the same reason of those being edge cases I think it is also fine having an unicode that is very rare and hardly supported by most fonts.

ok sounds good to me. I'll put the policy at the top of the gaiji map. Should probably go through and check all the maps are in line with the policy as well, but I can't get to that until next week at least.

the icon map currently has a couple icon-代用字, you could say. For example kigo.svg and bungo.png
image

IIRC, shoui was pretty adamant about using unicode whenever possible. I think the reason was to avoid issues with svgs/html etc when making anki cards with yomichan

yomichan has proper support for inserting svgs etc into anki now, so maybe not as much of an issue. but it doesn't work if you manually copy paste straight from yomichan into anki, ofc (like I do)
image

this isnt an issue for gaiji, cos they are pretty rare. but kigo.svg and bungo.png are in a huge portion of entries

it would be nice to have a unified policy between the gaiji/icon map, and unified maps between yomichan/mdict versions though. so maybe I'll just revert those icon-代用字 to svg and put up with a couple images

> Concerning the font issue you should install 花園

thanks ill check it out!

**Comment by epistularum** [comment]
>the icon map currently has a couple icon-代用字, you could say. For example kigo.svg and bungo.png
...
this isnt an issue for gaiji, cos they are pretty rare. but kigo.svg and bungo.png are in a huge portion of entries

I think it's fine using replacement for those to go around the limitations of yomichan as they do not relate directly to the accuracy (intention) of the definition, it's really just formatting. As you said they're really frequent so they're unavoidable anyways.

>but it doesn't work if you manually copy paste straight from yomichan into anki, ofc (like I do)

Which is honestly the best way to make a proper card, I agree. I wonder if it is technically possible to export svgs when using the {selection-text} function or something.

**Comment by Thermospore** [comment]
> I think it's fine using replacement for those to go around the limitations of yomichan as they do not relate directly to the accuracy (intention) of the definition, it's really just formatting. As you said they're really frequent so they're unavoidable anyways.

hmm yeah this seems like a good way to go. I went ahead and:
- left the icon maps as is
- [reverted these svgs back to unicode](https://github.com/Thermospore/koj72yomi/commit/b9262b2fd296d93a44e952e542eaf8f26ba92c0d)
- [added a mapping policy to the top of the gaiji map](https://github.com/Thermospore/koj72yomi/commit/745cfff9081b02bef249ef9bdabb2b08c643a98c)

will go through the gaiji map to make sure everything checks out

> Which is honestly the best way to make a proper card, I agree. I wonder if it is technically possible to export svgs when using the {selection-text} function or something.

is {selection-text} a handlebars thing? tbh I actually haven't gotten around to trying yomichan's anki integration, so I'm not familiar. I always got the impression lots of people use it though

**Comment by epistularum** [comment]
>is {selection-text} a handlebars thing? tbh I actually haven't gotten around to trying yomichan's anki integration, so I'm not familiar. I always got the impression lots of people use it though

It is not a handlebars thing, it's in the anki export thingy.
image

**Pull request merged**
